name: Auto Update Loto

on:
  schedule:
    - cron: '0 13 * * 2'
 workflow_dispatch:

permissions:
  contents: write
  
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリ取得
        uses: actions/checkout@v3

      - name: ミニロト結果更新
        run: |
          echo '{
            "game": "miniloto",
            "round": "AUTO",
            "draw_date": "'$(date +%Y-%m-%d)'",
            "main": ["03","11","20","25","28"],
            "bonus": "10",
            "updated_at": "'$(date +%Y-%m-%d)'"
          }' > data/miniloto_latest.json

      - name: ナンバーズ4更新
        run: |
          echo '{
            "game": "numbers4",
            "result": "5678",
            "updated_at": "'$(date +%Y-%m-%d)'"
          }' > data/numbers4_latest.json

      - name: Git更新
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "auto update loto result" || echo "no changes"
          git push
